sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
services:
  - redis-server
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=Q7IRJzqV8gYttEKTjGk4gYEcN5eJCyufq
  - "[ $CXX = g++-6 ] && cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON . || true"
  - "[ $CXX = clang++-3.8 ] && cmake -DCMAKE_BUILD_TYPE=Debug . || true"
  - make tests -j4
  - ./tests
  - "[ $CXX = g++-6 ] && make coveralls || true"
