sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    - g++-7
    - clang-5.0
    - lcov
install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-5.0 || true"
script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=Q7IRJzqV8gYttEKTjGk4gYEcN5eJCyufq
  - "[ $CXX = g++ ] && cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON . || true"
  - "[ $CXX = clang++ ] && cmake -DCMAKE_BUILD_TYPE=Debug . || true"
  - make -j4
  - ./tests
  - make coveralls
